name: Lint and Test Helm Charts

on:
  push:
    paths:
      - 'charts/selenium-grid/**'
  pull_request:
    paths:
      - 'charts/selenium-grid/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config tests/chart-test.yaml)
          if [[ -n "$changed" ]]; then
            echo "{changed}={true}" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config tests/chart-test.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        run: ct install --all --config tests/chart-test.yaml

      - name: Deploy Chart via Helm
        run: |
          helm install selenium-grid charts/selenium-grid --namespace selenium-grid-test --create-namespace       
          sleep 300s # To be improved via a dyncmic health check

      - name: Run Test cases Against Kubernetes
        run: |
          chmod 775 ./tests/bootstrapKINDTests.sh
          ./tests/bootstrapKINDTests.sh   
