name: Lint and Test Helm Charts

on:
  push:
    paths:
      - 'charts/selenium-grid/**'
  pull_request:
    paths:
      - 'charts/selenium-grid/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config tests/chart-test.yaml)
          if [[ -n "$changed" ]]; then
            echo "{changed}={true}" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config tests/chart-test.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
         config: ./tests/kind-cluster-config.yaml

# 👋 Documentation link for Ingress Installation on kind k8s cluster https://kind.sigs.k8s.io/docs/user/ingress
      - name: Install ingress-nginx on kind kubernetes cluster
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl wait --namespace ingress-nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=90s

      - name: Run chart-testing (install)
        run: ct install --all --config tests/chart-test.yaml

      - name: Deploy Selenium Grid Chart via Helm 
        run: |
          helm install selenium-grid -f ./tests/override-kind-auth-values.yaml charts/selenium-grid --namespace selenium-grid-test --create-namespace
          kubectl get ingress --all-namespaces

      - name: Wait for Grid deployment to be ready ⏰
        timeout-minutes: 5
        run: |
          # Test if grid is accessible via Ingress on http://localhost
          url="http://localhost/status"
          status_code=0
          while [ $status_code -ne 200 ]
          do
              response=$(curl -s -o /dev/null -w "%{http_code}" $url)
              status_code=$(echo $response | tr -d '\n')
              sleep 1
          done
          echo "Selenium Grid is ready.HTTP 200 status received. 🚀"

      - name: Get pods 
        run: |
          kubectl get pods -n selenium-grid-test

      - name: Run Smoke Test Against Kubernetes
        run: |
          python ./tests/K8sSmokeTest.py "http://localhost"
          chmod 755 ./tests/bootstrapKINDTests.sh
          export SELENIUM_GRID_HOST=localhost
          export SELENIUM_GRID_PORT=80
          ./tests/bootstrapKINDTests.sh
      - name: Get pods again
        run: |
          kubectl get pods -n selenium-grid-test
